services:
  sonarqube:
    image: 'sonarqube:25.11.0.114957-community'
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: 'jdbc:postgresql://db:5432/sonar'
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'
      - 'sonarqube_logs:/opt/sonarqube/logs'
      - 'sonarqube_temp:/opt/sonarqube/temp'
    networks:
      - sonarqube
    ports:
      - '9000:9000'
  db:
    image: 'postgres:17.5'
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - 'postgresql:/var/lib/postgresql'
      - 'postgresql_data:/var/lib/postgresql/data'
    networks:
      - sonarqube
volumes:
  sonarqube_data: null
  sonarqube_extensions: null
  sonarqube_logs: null
  sonarqube_temp: null
  postgresql: null
  postgresql_data: null
networks:
  sonarqube: null
